### ISSUE TITLE
Example doesn't compile for macOS

### ISSUE THREAD

**Issue by DevulderJeanPaul** [flocked/AdvancedCollectionTableView#12]
Hi,

error are:
Potential overridden instance method 'startDownload(using:completionHandler:)' here (WebKit.WKWebView)
Potential overridden instance method 'resumeDownload(fromResumeData:completionHandler:)' here (WebKit.WKWebView)

The problem are in FZUIKIt file FZWebView

XCode 16.1, macOS 15.1 (24B83)

**Comment by DevulderJeanPaul** [comment]
![Capture d’écran 2024-11-18 à 14 29 15](https://github.com/user-attachments/assets/63245835-499c-4e89-9e9f-e9cb5a5c6d35)

**Comment by flocked** [comment]
Fixed it with the newest release of FZUIKit.

**Comment by DevulderJeanPaul** [comment]
Thanks,
