### ISSUE TITLE
The example program crashed, guess it was caused by Swizzle.

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/AdvancedCollectionTableView#8]
<img width="1943" alt="iShot_2023-07-22_01 35 33" src="https://github.com/flocked/AdvancedCollectionTableView/assets/61279231/21e09882-724f-4dec-b1a0-a11f8729b449">

**Comment by flocked** [comment]
Its fixed.

**Comment by flocked** [comment]
Its fixed. The API isn't swizzling anymore.
