### ISSUE TITLE
Interested in supporting NSOutlineView?

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/AdvancedCollectionTableView#9]
I can provide support similar to NSOutlineViewDiffableDataSource

I found this a few method through reverse engineering, in the case of don't need to implement the delegate method to NSTableView provide the data. I'm guessing this is probably reserved for the NSTableViewDiffableDataSource

```swift
@objc
protocol NSTableViewInternalDataSource: NSTableViewDataSource {
    @objc(_tableView:viewForTableColumn:row:)
    func _tableView(_ tableView: NSTableView, viewFor tableColumn: NSTableColumn?, row: Int) -> NSView?
    @objc(_tableView:rowViewForRow:)
    func _tableView(_ tableView: NSTableView, rowViewForRow row: Int) -> NSTableRowView?
    @objc(_tableView:isGroupRow:)
    func _tableView(_ tableView: NSTableView, isGroupRow row: Int) -> Bool
}
```
But when I asked through TSI support if it had the same reservation for NSOutlineView, I got a negative response, which means that we may need to go through a delegate proxy to forward the.

**Comment by flocked** [comment]
Thanks! I'm already expose the mentioned methods (see `Extensions/NSTableView/NSTableViewDiffableDataSource+`).

**Comment by Mx-Iris** [comment]
So do you have plans to support NSOutlineView?

**Comment by flocked** [comment]
I might support it in the future. I already have some working code on my Mac for a diffable outline datasource, but it's far from finished and not my mine focus. 

My current priority is to improve `NSItemContentConfiguration` and `NSListContentConfiguration`. 

I also have already wrote advanced iOS diffable collection and table datasources that adds all the same handlers and methods like my Mac counterparts. I'm unsure if I should include them in this repository or create a separate on.

**Comment by Mx-Iris** [comment]
Ok, I understand. I hope you can incorporate more UIKit design into AppKit. I'm very interested in it
